### ISSUE TITLE
Tedac Display Mode switch

### ISSUE THREAD

**Issue by Michael3478** [BlueFinBima/DCS-AH-64D-Profile#12]
Hello
I noticed that the Day and Off positions on the Teadc display mode switch are swapped,
I have corrected these in the interface.
If this is the right way, could this fix possibly be used in the next update?
Thanks for your great work.

greeting
Michael

![Tedac Display Mode switch](https://github.com/BlueFinBima/DCS-AH-64D-Profile/assets/155083349/5ead4ee7-774f-40c3-8c37-0c1a6aa33b8f)

**Comment by BlueFinBima** [comment]
Hi Michael, thanks for raising this.  If the problem is with the interface, then typically you would raise the issue against the repository which contains the interface which would either be the repo for [Helios](https://github.com/HeliosVirtualCockpit/Helios) or [HeliosInterfaces](https://github.com/HeliosVirtualCockpit/HeliosInterfaces).
Anyway, I'll look into the issue you've raised, and open an issue in the correct repository to resolve it.
Cheers,  BlueFin

**Comment by Michael3478** [comment]
Hi BlueFin
Thank you for the information. I will do this like this in the future.

greeting
Michael

**Comment by BlueFinBima** [comment]
Re-opening so I don't forget about this

**Comment by BlueFinBima** [comment]
https://github.com/HeliosVirtualCockpit/Helios/issues/814 opened in Helios repo to progress this issue.
